import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-info',
  templateUrl: './info.component.html',
  styleUrls: ['./info.component.css']
})
export class InfoComponent implements OnInit {
  public langsList = [
    'Africaans',
    'Albanés',
    'Alemán',
    'Amárico',
    'Árabe (Arabizi)',
    'Arábica',
    'Armenio',
    'Azerbaiyano',
    'Bengalí',
    'Bielorruso',
    'Bihari',
    'Búlgaro',
    'Catalán',
    'Cebuano',
    'Checo',
    'Cherokee',
    'Chino (simplificado)',
    'Chino (tradicional)',
    'Coreano',
    'Croata',
    'Danés',
    'Dari',
    'Eslovaco',
    'Esloveno',
    'Español',
    'Estonio',
    'Finlandés',
    'Francés',
    'Francés (Canadá)',
    'Galés',
    'Gallego',
    'Ganda',
    'Georgiano',
    'Griego',
    'Gujarati',
    'Hausa',
    'Hebreo',
    'Hindi',
    'Hmong',
    'Holandés',
    'Húngaro',
    'Indonesio',
    'Inglés',
    'Inuktitut',
    'Irlandesa',
    'Islandés',
    'Italiano',
    'Japonés',
    'Javanés',
    'Kannada',
    'Kinyarwanda',
    'Letón',
    'Limbu',
    'Lituano',
    'Macedónio',
    'Malayalam',
    'Malayo',
    'Maltés',
    'Marathi',
    'Nepalí',
    'Noruego',
    'Oriya',
    'Osetio',
    'Pashto',
    'Persa',
    'Polaco',
    'Portugués',
    'Portugués (Brasil)',
    'Portugués (portugal)',
    'Rumano',
    'Ruso',
    'Serbio',
    'Siríaco',
    'Somalí',
    'Sueco',
    'Sundanés',
    'Swahili',
    'Tagalo',
    'Tailandés',
    'Tamil',
    'Tayiko',
    'Telugu',
    'Turco',
    'Ucranio',
    'Urdu',
    'Uzbeko',
    'Vasco',
    'Vietnamita',
    'Yídish'
  ]

  constructor() { }

  ngOnInit(): void {
  }

}
