import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-info-versions',
  templateUrl: './info-versions.component.html',
  styleUrls: ['./info-versions.component.css']
})
export class InfoVersionsComponent implements OnInit {

  public SDL = {
    langsList: [
      'Africaans',
      'Albanés',
      'Alemán',
      'Amárico',
      'Árabe (Arabizi)',
      'Arábica',
      'Armenio',
      'Azerbaiyano',
      'Bengalí',
      'Bielorruso',
      'Bihari',
      'Búlgaro',
      'Catalán',
      'Cebuano',
      'Checo',
      'Cherokee',
      'Chino (simplificado)',
      'Chino (tradicional)',
      'Coreano',
      'Croata',
      'Danés',
      'Dari',
      'Eslovaco',
      'Esloveno',
      'Español',
      'Estonio',
      'Finlandés',
      'Francés',
      'Francés (Canadá)',
      'Galés',
      'Gallego',
      'Ganda',
      'Georgiano',
      'Griego',
      'Gujarati',
      'Hausa',
      'Hebreo',
      'Hindi',
      'Hmong',
      'Holandés',
      'Húngaro',
      'Indonesio',
      'Inglés',
      'Inuktitut',
      'Irlandesa',
      'Islandés',
      'Italiano',
      'Japonés',
      'Javanés',
      'Kannada',
      'Kinyarwanda',
      'Letón',
      'Limbu',
      'Lituano',
      'Macedónio',
      'Malayalam',
      'Malayo',
      'Maltés',
      'Marathi',
      'Nepalí',
      'Noruego',
      'Oriya',
      'Osetio',
      'Pashto',
      'Persa',
      'Polaco',
      'Portugués',
      'Portugués (Brasil)',
      'Portugués (portugal)',
      'Rumano',
      'Ruso',
      'Serbio',
      'Siríaco',
      'Somalí',
      'Sueco',
      'Sundanés',
      'Swahili',
      'Tagalo',
      'Tailandés',
      'Tamil',
      'Tayiko',
      'Telugu',
      'Turco',
      'Ucranio',
      'Urdu',
      'Uzbeko',
      'Vasco',
      'Vietnamita',
      'Yídish'
    ],
    fileTypes: [
      '.txt',
      '.xline',
      '.htm, .html, .xhtml',
      '.xml',
      '.sdlxml',
      '.tmx',
      '.xliff',
      '.bcm',
      '.pdf',
      '.rtf',
      '.docx, .dotx, .docm, .dotm',
      '.xlsx, .xltx, .xlsm, .xltm, .xlam, .xlsb',
      '.pptx, .potx, .ppsx, .pptm, .potm, .ppsm',
      '.doc, .dot',
      '.xls, .xlt, .xla',
      '.ppt, .pot, .pps',
      '.odt',
      '.ods',
      '.odp',
      '.gif',
      '.jpg, .jpeg',
      '.png',
    ],
    fileLimits: '100 mb',
    filePermanency: '1 descarga / 2 horas'
  }

  public DEEPL = {
    langsList: [
      'Alemán',
      'Búlgaro',
      'Checo',
      'Chino',
      'Danés',
      'Eslovaco',
      'Esloveno',
      'Español',
      'Estonio',
      'Finlandés',
      'Francés',
      'Griego',
      'Holandés',
      'Húngaro',
      'Inglés',
      'Italiano',
      'Japonés',
      'Letón',
      'Lituano',
      'Polaco',
      'Portugués',
      'Rumano',
      'Ruso',
      'Sueco',
    ],
    fileTypes: [
      '.docx',
      '.pptx',
      '.htm, .html',
      '.txt',
    ],
    fileLimits: '10 mb / 1.000.000 caracteres',
    filePermanency: '1 descarga'
  }

  constructor() { }

  ngOnInit(): void {
  }

}
